/**
 * Ported from
 * `as-sources/legacy-generators-base-library/ro/se/legacy/generators/constants/GeneratorKeys.as`.
 */
export const GeneratorKeys = {
  ALL_GENERATION_DONE: 'allGenerationDone',
  AUTHOR_EMAIL: 'generatorAuthorEmail',
  AUTHOR_NAME: 'generatorAuthorName',
  AUTHOR_SITE: 'generatorAuthorSite',
  AVAILABLE_GENERATORS_LIST: 'availableGeneratorsList',
  CONFIGURATION_DATA: 'configurationData',
  COPYRIGHT: 'generatorCopyright',
  DESCRIPTION: 'generatorDescription',

  GEN_CFG_DATASET: 'genCfgDataset',
  GEN_CFG_UI_BLUEPRINT: 'genCfgUiBlueprint',
  GEN_CFG_WINDOW_CLOSE: 'genCfgWindowClose',
  GEN_CFG_WINDOW_COMMIT: 'genCfgWindowCommit',
  GLOBAL_UID: 'generatorGlobalUid',
  UNRECOGNIZED_GENERATOR:
    'The current project contains an unknown generator "%s" that could not be initialized.',
  INITIALIZED_GENERATOR: 'initializedGenerator',
  INITIALIZED_GENERATORS_LIST: 'initializedGeneratorsList',
  INPUTS_DESCRIPTION: 'generatorInputsDescription',
  INPUT_CONNECTIONS: 'generatorInputConnections',
  MAIN_CLASS: 'generatorMainClass',
  CONFIGURATION_UI_CLASS: 'generatorCfgUiClass',
  NAME: 'generatorFriendlyName',
  NEED_GEN_CFG: 'needGenCfg',
  NEED_GEN_CFG_FORCE_CLOSED: 'needGenCfgForceClosed',
  GENERATOR_BINDING_REQUEST: 'needGenDefaultData',
  NEED_GEN_EXECUTION: 'needGenExecution',
  NEED_GEN_OUTPUT_TARGETS: 'needGenOutputTargets',
  NEED_GEN_PROMPT: 'needGenPrompt',
  NEED_GEN_DIALOG: 'needGenDialog',
  NONE: 'none',
  OUTPUTS_DESCRIPTION: 'generatorOutputsDescription',
  OUTPUT_CONNECTIONS: 'generatorOutputConnections',
  OUTPUT_TARGETS: 'outputTargets',
  PROJECT_GENERATORS_READY: 'projectGeneratorsReady',
  QUEUE_EXHAUSTED: 'queueExhausted',
  QUEUE_POSITION_EXHAUSTED: 'queuePositionExhausted',
  RELEASE_DATE: 'generatorReleaseDate',
  REQUIRED_GENERATORS_LIST: 'requiredGeneratorsList',
  SLOT_DATA_TYPE: 'slotDataType',
  SLOT_NAME: 'slotName',
  TARGETS_INFO: '$targetsInfo',
  VERSION: 'generatorVersion',
  NEED_GEN_UIDS: 'needGenUids',
  GEN_UIDS_LIST_READY: 'genUidsListReady',
  STATUS_CHANGED: 'statusChanged',
  GEN_ABORT_REQUESTED: 'genAbortRequested',
  GEN_MINIMIZE_REQUESTED: 'genMinimizeRequested',
  UI_GENERATOR_CONFIG: 'uiGeneratorConfig',
  ANIMATED_PARAMETER_UIDS: 'animatedParameterUids',
  PARAMETERS: 'generatorParameters',
  ANIMATED_PARAMETERS: 'animatedParameters',

  SECTION_TARGETS: 'Score Sections',
  GENERATION_STATUS_TEMPLATE: 'Generation %s',
  GENERATION_IN_PROGRESS: '%s is producing content. Please wait...',
  GENERATION_COMPLETED: 'Execution of %s completed normally.',
  GENERATION_ABORTED: '%s halted execution on user request.',
  GENERATION_ERROR: '%s encountered an error.',
} as const;
